### ISSUE TITLE
Redirect to authorize endpoint is to http when behind load balancer terminating SSL

### ISSUE THREAD

**Issue by Toominator** [IdentityServer/IdentityServer3.Admin#30]
I have IdentityServer3 and Admin in the same host behind a load balancer and I am terminating SSL at the load balancer.
I therefore have RequireSsl=false and the PublicOrigin of IdentityServer set to the https address of the load balancer.
When logging in to Admin the redirect is to http instead of https and so fails
(e.g. http://identity.abc.com/admin/authorize?state=1180072232507164&client_id=idAdmin&response_type=token)

**Comment by alhardy** [comment]
Same setup works fine for me.

Do you have the Authority on ```OpenIdConnectAuthenticationOptions``` set as https in the Admin?

**Comment by Toominator** [comment]
Yes, I do.


And you have RequiresSsl = false in your AdminHostSecurityConfiguration ?


________________________________

**Comment by senseicz** [comment]
When you terminate SSL on load balancer, this balancer will in most cases add special HTTP header "X-Forwarded-Proto" with value either http or https to give back-end server an idea whether initial call was over http or https. 
Without further thinking what it may cause, maybe it would be enough just to modify condition in `IdentityAdminAppBuilderExtensions.cs`, something like changing following code:

```
app.Use(async (ctx, next) =>
{
     if (!ctx.Request.Scheme.Equals("https", StringComparison.OrdinalIgnoreCase) && 
         options.AdminSecurityConfiguration.RequireSsl)
    {
          ctx.Response.Write("HTTPS required");
    }
    else
    {
         await next();
    }
});
```
to:
```
app.Use(async (ctx, next) =>
{
	if (!string.IsNullOrEmpty(ctx.Request.Headers["X-Forwarded-Proto"])) //behind load balancer
	{
		if (!ctx.Request.Headers["X-Forwarded-Proto"].Equals("https", StringComparison.OrdinalIgnoreCase) &&
			options.AdminSecurityConfiguration.RequireSsl)
		{
			ctx.Response.Write("HTTPS required");
		}
		else
		{
			await next();
		}
	}
	else //direct traffic
	{
		if (!ctx.Request.Scheme.Equals("https", StringComparison.OrdinalIgnoreCase) &&
			options.AdminSecurityConfiguration.RequireSsl)
		{
			ctx.Response.Write("HTTPS required");
		}
		else
		{
			await next();
		}
	}
});

```

Although question is what it will do next when AccessToken is returned upon login.

**Comment by KMC13** [comment]
I have had a go at getting in the same scenario. Https terminating at load balancer with http between load balancer and the web servers.

@senseicz this was very useful but it only got me one hop of the way.
When you click login it goes to the /authorize endpoint. Because the OAuthAuthorizationServer server is now running requiring ssl this request fails as the request comes in as http.

So, I tried again using RequireSsl false on the IdentityAdmin.

The problem that I can see is when the identity server responds it first POST's the identity token to the admin endpoint https://myserver/admin which responds with a 302 and Location
http://myserver/admin/authorize?state=13284069124445454&client_id=idAdmin&response_type=token

This is where it obviously can't find the endpoint as it is http and needs to be https. I cant work out where this POST request is handled in IdentityAdmin. The weird bit is it doesnt seem to come through the OWIN pipeline at all. 

The only thought I had to solve this was a bit of OwinMiddleware that intercepts this response modifying the Location to be the https address. However, as I said the POST from the IdentityServer to the IdentityAdmin endpoint doesn't seem to go through the IdentityAdmin OWIN pipeline. 

Any other ideas anyone?

**Comment by KMC13** [comment]
Doh. I didn't put my OWIN Middleware early enough in the pipeline. I finally got this "working". i.e. It's a hack.

1. I put in the following middleware at the top of my pipeline before the CookieAuthentication used by IdentityAdmin Server.

app.Use(async (ctx, next) =>
{
    await next();
                    
    if (ctx.Response.StatusCode == 302 && ctx.Response.Headers.Any(x => x.Key == "Location"))
    {
        ctx.Response.Headers["Location"] = ctx.Response.Headers["Location"].Replace("http://", "https://");
    }
});

2. Then I faced another issue. The API seems to implement a HAL like standard and it uses absolute urls. This means that all the urls generated by the MetaController are http addresses as to it that is correct because https is terminated at the load balancer. This results in a Access Denied header when making the Ajax request to get clients.

So, to cludge this until I think of a better plan I replace the protocol on all the links. i.e. .Replace("http://", "https://")

**Comment by KMC13** [comment]
The solution I can up with for the AbsoluteUri's used in the REST API was to make them relative to the authority. See pull request #38

**Comment by iBoonz** [comment]
Merged pull request, ty @KMC13

**Comment by senseicz** [comment]
May I ask for these changes to made a new beta release and push them out via new NuGet package? Would help me a lot, many thanks in advance :-)
