### ISSUE TITLE
Admin Setup - Best Practices

### ISSUE THREAD

**Issue by markgmarkg** [IdentityServer/IdentityServer3.Admin#37]
Hi,

What is a recommended method to install the administration tool?
Should we install the latest Identity Server bits, and then add Admin package?

Please, clarify the procedure.

Regards,
Mark

**Comment by iBoonz** [comment]
Hi, 

You can just create a new project and add some nuget packages: 
Thinktecture.IdentityServer3
IdentityServer3.Admin 
IdentityServer3.Admin.EntityFramework  (if you want to use EF)

These are the key packages you need for the admin tool.

Tip: You can always download this github project, open it in your IDE, and check the HOST project, that is a demo project with minimal setup

**Comment by markgmarkg** [comment]
Thank you.

**Comment by fcartu** [comment]
Hi @iBoonz, for a production environment, what is the recommend way to do it? I'm stuck with a test deployment because I'm not able to login to the admin website with this error:

 **The client application is not known or is not authorized.**

How could configure it if it is the first time installation, I couldn't create this client inside IS if I'm not able to login to it.

What's your advice in this case?

**Comment by naymore** [comment]
I have the same question. I do realize the admin application needs to be authorized itself, anything else would be crazy. Still I wonder how to do that.

I do have a custom "install routine" that adds a User to the UserStore.
Do I need to do the same for a Client?

> You can download the git solution and explore the host project, Also the Admin is very similar to the identitymanager, and this got a nice wiki, so you can check that out.

Couldn't find any "identitymanager" project on github - or wiki.

**Comment by iBoonz** [comment]
Github:
[Linkie](https://github.com/IdentityManager/IdentityManager)
Wiki:
[Linkie 2](https://github.com/IdentityManager/IdentityManager/wiki)
